ALTER TABLE "Teacher"
ADD COLUMN "notes" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TABLE "ClassGroup"
ADD COLUMN "studentCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "maleStudentCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "femaleStudentCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "weeklyScoreHistory" JSONB NOT NULL DEFAULT '[]'::jsonb,
ADD COLUMN "notes" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
